### ISSUE TITLE
Will it be published to the Marketplace?

### ISSUE THREAD

**Issue by elor** [chylex/IntelliJ-Inspection-Lens#1]
Love this plugin, it's so handy, and should have been part of the JetBrains IDEs from the start!

Will it be available on the marketplace for ease of use?

Thanks again!

**Comment by chylex** [comment]
Sure, I can do it sometime this week. Need to prepare a README, screenshots, etc. first.

**Comment by chylex** [comment]
https://plugins.jetbrains.com/plugin/19678-inspection-lens
