### ISSUE TITLE
Support right-aligned inspections

### ISSUE THREAD

**Issue by nicolaslara** [chylex/IntelliJ-Inspection-Lens#11]
Thanks for making this plugin! it works great and I've been lacking this in intellij for a while. 

It would be great if it could support displaying the inspections right-aligned so that they're easier to read and differentiate from the code. 

I can try to work on this when I get some free time and submit a PR, but leaving the issue here in case someone can get to it before I do.

**Comment by chylex** [comment]
Can you explain or show how right-aligned inspections look? I don't recall this being an option in the IntelliJ SDK and don't think I saw anything like that before.

**Comment by chylex** [comment]
Closing due to no response.

**Comment by nicolaslara** [comment]
Ahh sorry! Completely missed the first reply. Here's a screenshot of what I meant:
![08xmT.png](https://user-images.githubusercontent.com/37868/232197039-e8e58b4e-92bf-4ebc-917e-2a6a0af88180.png)

**Comment by chylex** [comment]
I don't see anything in the IntelliJ SDK that could right-align inlay hints; I'm sure it would be possible with a sufficient level of hackery but that's not appropriate for this plugin. I could see someone making a separate plugin that adds general support for right-aligned inlay hints.

**Comment by nicolaslara** [comment]
That makes sense! Thanks for looking into it anyway 😊
