### ISSUE TITLE
Not showing at the end

### ISSUE THREAD

**Issue by pentatonicfunk** [chylex/IntelliJ-Inspection-Lens#21]
anyone know why this happen ?
![image](https://github.com/chylex/IntelliJ-Inspection-Lens/assets/831674/e0dd6004-ea33-4a8b-8987-7c8a5415075d)
instead of displayed at the end of line, it display in the middle of it

**Comment by chylex** [comment]
I don't think I've seen it before, so I'll need more information about how to reproduce it.

**Comment by pentatonicfunk** [comment]
i think its because i was using Jetbrains gateway ?
So basically i've setup jetbrains gateway on the server, the settings would have 
- Plugins - Host
- Plugins - Client
I've tried enabled inspection lens in the Plugins - Client, but its just errored out with something about Class not found, iirc. And then enabled via Plugins - Host instead, it works but with above behavior.
Im using Mac OS for the Gateway client.

Not sure how hard for you to replicate the gateway setup, but if you willing to, i can try make disposable setup and share it here ? i dont mind privacy, it would be disposable.

**Comment by chylex** [comment]
I have Gateway, don't really use it because I find it too buggy, but I can look into it when I have time.

**Comment by pentatonicfunk** [comment]
> I have Gateway, don't really use it because I find it too buggy, but I can look into it when I have time.

thank you!.

I was actually planning to use gateway as primary instead, between our codebase only getting bigger, and PHPStorm ( in my own experience ) getting slower in each updates. Basically the option would be always upgrading my workstation to keep up with it, so the thinking of using gateway is the load would be in the server, and the client -- my workstation can have small specs + remote everywhere kinda nice.

The caveat though, cost, server that can keep up with the JetBrains gateway + huge codebase also not cheap, and its gonna be persistent monthly ( hourly ) cost. Cheapest 4CPU + 8GB RAM is $48 in DO.

Unlike DO, AWS has hibernate option that not billed, but i imagine trying to remember to hibernate it every time its not needed is still annoying.

**Comment by chylex** [comment]
I can reproduce the issue but the IntelliJ SDK does not seem to support debugging plugins on the remote backend (https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/894).

What seems to be happening is Gateway does not support the `addAfterLineEndElement` API properly, and it just renders inlays at their actual offset (1 character before the end of the highlight, which is what's happening on the screenshot) instead of after the line.

It seems like a Gateway issue that should be reported to JB. Either way, the SDK does not let me debug it so I can't say for sure.

**Comment by chylex** [comment]
I will be able to fix the missing class error when installed on the Gateway Client, and see if there's a way to block the plugin from installing on the Remote.
