### ISSUE TITLE
Issues with rendered documentation comments

### ISSUE THREAD

**Issue by igor-akhmetov** [chylex/IntelliJ-Inspection-Lens#26]
Hello,
It seems inspection lens causes some issues when there are inspections inside rendered documentation comments, e.g.:
![image](https://github.com/user-attachments/assets/59f9e66e-4238-467e-aa87-b753ab93c031)
The original source code was this (C++ in Rider, but shouldn't matter):
```
enum Test
{
	/// The value is optional, and may specify a name override for the method.
	A,

	/// UPARAM
	B,
};
```

**Comment by dkjb634** [comment]
chylex, Feel free to join JetBrains plugin-writers community should you need any assistance. You can join it from the here: https://plugins.jetbrains.com/slack
The channel for Rider is '#dotnet-pluginwriters'

**Comment by chylex** [comment]
Looks like a conflict between the documentation renderer, and the plugin's range highlighter that adds the line background. Interesting.
