### ISSUE TITLE
Displays class visibility error even when using shouldAllowMockingProtectedMethods 

### ISSUE THREAD

**Issue by csandreas1** [chylex/IntelliJ-Inspection-Lens#27]
Error shouldn't be shown since I allow mocking protected method either directly in the test or from the setUp()

![image](https://github.com/user-attachments/assets/6e5893d6-0a5e-4d27-a846-3f841fd6b8c8)

**Comment by chylex** [comment]
The plugin just shows errors reported by your IDE.
