### ISSUE TITLE
Command for hotkeys to jump to the next / previous inspection?

### ISSUE THREAD

**Issue by schittli** [chylex/IntelliJ-Inspection-Lens#30]
Hello
**Thank you very much for sharing your great work!**

It's scary, but the JetBrains IDEs don't have a command to bind to a hotkey to jump to the previous or next inspection. They just support jumping between Errors.

Could you please consider offering these two commands in your plugin?
I guess that your plugin already has almost all the code to enable such hotkeys 😃 

Thanks a lot, kind regards,
Thomas

**Comment by chylex** [comment]
Settings - Editor - Code editing - The 'Next Error' action goes through: All problems

**Comment by schittli** [comment]
Thank you very much, @chylex , for your help.

It is very disappointing JetBrains does not offer two commands, one for real errors and one for suggestions / warnings. 

**❯ Jetbrains Users must change the settings(!) to change the behavior for a simple command.** 
In 2024, that's pretty embarrassing.

It is even more disappointing that JetBrains has not yet found the motivation to adopt modern concepts such as VS Code, where all internal IDE commands are made available to the customer. The user can completely free define the Keyboard mapping and can even pass Parameters to IDE Commands so that they serve him as he needs them.

But your answer was still very helpful, so we're able to find workarounds, thank you very much.

Kind regards,
Thomas
