### ISSUE TITLE
Inspections Lens Slow on 2022.3 build of ideas

### ISSUE THREAD

**Issue by AlNotAlbert** [chylex/IntelliJ-Inspection-Lens#6]
Very Slow, Sometimes has ghost errors on the newest jetbrains ides

**Comment by chylex** [comment]
I've been using 2022.3 since the EAPs came out and I'm not seeing any performance issues, so I will need a reproducible test case and/or a profile that shows what the plugin is doing when the slowness occurs.

**Comment by chylex** [comment]
Closing due to no response.
