### ISSUE TITLE
Awesome plugin.. a maybe big request but could you integrate, total ts errors?

### ISSUE THREAD

**Issue by Jarrodsz** [chylex/IntelliJ-Inspection-Lens#7]
Awesome plugin.. a maybe big request but could you integrate, total ts errors?

https://github.com/mattpocock/ts-error-translator

I have been looking to make a intellj plugin myself but never build one and no idea where to start.

**Comment by chylex** [comment]
Hi, this plugin is intended to be fairly minimal, so any integrations would be best for a separate plugin or a fork.
