### ISSUE TITLE
I have a suspicion that this plugin is causing IntelliJ being quite slow

### ISSUE THREAD

**Issue by SimY4** [chylex/IntelliJ-Inspection-Lens#8]
Tested it on a multi-module, multi-language gradle project with Java/Scala/Kotlin mixed setup.

Disabling the plugin seems to help to give back the editor's responsiveness.

IntelliJ is running with 2Gbs of heap. Is there a recommended setting that you know of?

**Comment by chylex** [comment]
Same as #6, please provide a reproducible test case or a performance profile that shows the reason for the issue.

**Comment by SimY4** [comment]
@chylex I'm happy to give it to you provided some guidance on how to measure it.

**Comment by chylex** [comment]
I'm not sure what's available for you, I primarily use JProfiler which is expensive. IntelliJ Ultimate comes with a profiler if you already have a license, there's also Java Flight Recorder which seems free for non-commercial use.

Each tool has its own documentation, but most should be able to save CPU sampling snapshots to a file. I can open either JProfiler `.jps` snapshots or Flight Recorder `.jfr` snapshots, not sure about other formats if any exist.

Hopefully the profile shows that the plugin is spending a lot of time doing something, but there are many reasons why performance can suffer and it might be difficult to pinpoint why.

**Comment by chylex** [comment]
Closing due to no response.
